name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Self Grading
      id: self-grading
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Self Grading
        setup-command: npm install
        command: npm test
        timeout: 1
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SELF-GRADING_RESULTS: "${{steps.self-grading.outputs.result}}"
      with:
        runners: self-grading
